"""init

Revision ID: 8f8d60b86959
Revises: 
Create Date: 2026-05-06 23:54:34.961412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f8d60b86959'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('code_master',
    sa.Column('code_type', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('code_type', 'code')
    )
    op.create_table('code_translation',
    sa.Column('code_type', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('lang', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('code_type', 'code', 'lang')
    )
    op.create_table('countries',
    sa.Column('country_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('climate', sa.String(), nullable=True),
    sa.Column('track_bias', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('country_id')
    )
    op.create_table('game_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('week', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('generation_stats',
    sa.Column('stat_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('avg_speed', sa.Float(), nullable=True),
    sa.Column('avg_stamina', sa.Float(), nullable=True),
    sa.Column('trend_distance', sa.Float(), nullable=True),
    sa.Column('speed_ratio', sa.Float(), nullable=True),
    sa.Column('stamina_ratio', sa.Float(), nullable=True),
    sa.Column('balance_ratio', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('stat_id'),
    sa.UniqueConstraint('year')
    )
    op.create_table('historical_events',
    sa.Column('event_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('week', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_historical_events_year'), 'historical_events', ['year'], unique=False)
    op.create_table('snapshots',
    sa.Column('snapshot_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('week', sa.Integer(), nullable=True),
    sa.Column('data', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('snapshot_id')
    )
    op.create_table('traits',
    sa.Column('trait_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('inherit_rate', sa.Float(), nullable=True),
    sa.Column('mutation_rate', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('trait_id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('owners',
    sa.Column('owner_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('ideology', sa.String(), nullable=True),
    sa.Column('ideology_strength', sa.Float(), nullable=True),
    sa.Column('money', sa.Float(), nullable=True),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['countries.country_id'], ),
    sa.PrimaryKeyConstraint('owner_id')
    )
    op.create_table('races',
    sa.Column('race_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.Column('grade', sa.String(), nullable=True),
    sa.Column('distance', sa.Integer(), nullable=True),
    sa.Column('surface', sa.String(), nullable=True),
    sa.Column('turn', sa.String(), nullable=True),
    sa.Column('slope', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['countries.country_id'], ),
    sa.PrimaryKeyConstraint('race_id')
    )
    op.create_index(op.f('ix_races_name'), 'races', ['name'], unique=False)
    op.create_table('trainers',
    sa.Column('trainer_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('skill', sa.String(), nullable=True),
    sa.Column('personality', sa.String(), nullable=True),
    sa.Column('reputation', sa.Float(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('retire_age', sa.Integer(), nullable=True),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['countries.country_id'], ),
    sa.PrimaryKeyConstraint('trainer_id')
    )
    op.create_table('trait_translation',
    sa.Column('trait_id', sa.Integer(), nullable=False),
    sa.Column('lang', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['trait_id'], ['traits.trait_id'], ),
    sa.PrimaryKeyConstraint('trait_id', 'lang')
    )
    op.create_table('horses',
    sa.Column('horse_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('birth_year', sa.Integer(), nullable=True),
    sa.Column('sex', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('speed', sa.Float(), nullable=True),
    sa.Column('stamina', sa.Float(), nullable=True),
    sa.Column('father_id', sa.Integer(), nullable=True),
    sa.Column('mother_id', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('trainer_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('last_race_year', sa.Integer(), nullable=True),
    sa.Column('last_race_month', sa.Integer(), nullable=True),
    sa.Column('last_race_week', sa.Integer(), nullable=True),
    sa.Column('fatigue', sa.Float(), nullable=True),
    sa.Column('health', sa.Float(), nullable=True),
    sa.Column('mental', sa.Float(), nullable=True),
    sa.Column('temper', sa.String(), nullable=True),
    sa.Column('start_skill', sa.Float(), nullable=True),
    sa.Column('control', sa.Float(), nullable=True),
    sa.Column('running_style', sa.String(), nullable=True),
    sa.Column('front_affinity', sa.Float(), nullable=True),
    sa.Column('back_affinity', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['father_id'], ['horses.horse_id'], ),
    sa.ForeignKeyConstraint(['mother_id'], ['horses.horse_id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.owner_id'], ),
    sa.ForeignKeyConstraint(['trainer_id'], ['trainers.trainer_id'], ),
    sa.PrimaryKeyConstraint('horse_id')
    )
    op.create_index(op.f('ix_horses_birth_year'), 'horses', ['birth_year'], unique=False)
    op.create_index(op.f('ix_horses_name'), 'horses', ['name'], unique=False)
    op.create_table('owner_traits',
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('trait_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.owner_id'], ),
    sa.ForeignKeyConstraint(['trait_id'], ['traits.trait_id'], ),
    sa.PrimaryKeyConstraint('owner_id', 'trait_id')
    )
    op.create_table('race_calendar',
    sa.Column('race_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['race_id'], ['races.race_id'], ),
    sa.PrimaryKeyConstraint('race_id', 'year', 'month', 'week')
    )
    op.create_table('trainer_traits',
    sa.Column('trainer_id', sa.Integer(), nullable=False),
    sa.Column('trait_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['trainer_id'], ['trainers.trainer_id'], ),
    sa.ForeignKeyConstraint(['trait_id'], ['traits.trait_id'], ),
    sa.PrimaryKeyConstraint('trainer_id', 'trait_id')
    )
    op.create_table('horse_traits',
    sa.Column('horse_id', sa.Integer(), nullable=False),
    sa.Column('trait_id', sa.Integer(), nullable=False),
    sa.Column('strength', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['horse_id'], ['horses.horse_id'], ),
    sa.ForeignKeyConstraint(['trait_id'], ['traits.trait_id'], ),
    sa.PrimaryKeyConstraint('horse_id', 'trait_id')
    )
    op.create_table('pedigrees',
    sa.Column('horse_id', sa.Integer(), nullable=False),
    sa.Column('ancestor_id', sa.Integer(), nullable=False),
    sa.Column('generation', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ancestor_id'], ['horses.horse_id'], ),
    sa.ForeignKeyConstraint(['horse_id'], ['horses.horse_id'], ),
    sa.PrimaryKeyConstraint('horse_id', 'ancestor_id')
    )
    op.create_index('idx_pedigree_horse', 'pedigrees', ['horse_id'], unique=False)
    op.create_table('race_entries',
    sa.Column('entry_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=False),
    sa.Column('horse_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('trainer_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('expected_fitness', sa.Float(), nullable=True),
    sa.Column('priority', sa.Float(), nullable=True),
    sa.Column('risk', sa.Float(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['horse_id'], ['horses.horse_id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.owner_id'], ),
    sa.ForeignKeyConstraint(['race_id'], ['races.race_id'], ),
    sa.ForeignKeyConstraint(['trainer_id'], ['trainers.trainer_id'], ),
    sa.PrimaryKeyConstraint('entry_id'),
    sa.UniqueConstraint('race_id', 'horse_id', 'year', 'month', 'week', name='uq_entry')
    )
    op.create_table('race_results',
    sa.Column('race_id', sa.Integer(), nullable=False),
    sa.Column('horse_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('time', sa.Float(), nullable=True),
    sa.Column('prize', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['horse_id'], ['horses.horse_id'], ),
    sa.ForeignKeyConstraint(['race_id'], ['races.race_id'], ),
    sa.PrimaryKeyConstraint('race_id', 'horse_id', 'year', 'month', 'week')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('race_results')
    op.drop_table('race_entries')
    op.drop_index('idx_pedigree_horse', table_name='pedigrees')
    op.drop_table('pedigrees')
    op.drop_table('horse_traits')
    op.drop_table('trainer_traits')
    op.drop_table('race_calendar')
    op.drop_table('owner_traits')
    op.drop_index(op.f('ix_horses_name'), table_name='horses')
    op.drop_index(op.f('ix_horses_birth_year'), table_name='horses')
    op.drop_table('horses')
    op.drop_table('trait_translation')
    op.drop_table('trainers')
    op.drop_index(op.f('ix_races_name'), table_name='races')
    op.drop_table('races')
    op.drop_table('owners')
    op.drop_table('traits')
    op.drop_table('snapshots')
    op.drop_index(op.f('ix_historical_events_year'), table_name='historical_events')
    op.drop_table('historical_events')
    op.drop_table('generation_stats')
    op.drop_table('game_state')
    op.drop_table('countries')
    op.drop_table('code_translation')
    op.drop_table('code_master')
    # ### end Alembic commands ###
